### ISSUE TITLE
Please fix Error: in .read.metaboanalyst.lib("compound_db.rds") : object 'my.lib' not found

### ISSUE THREAD

**Issue by songjunjun** [xia-lab/MetaboAnalystR#102]
The error is caused by: **print()**, this function needs an argument, such as **print("")**
MetaboAnalystR/R/general_data_utils.R: line 936, 952, 962.

@xia-lab

**Comment by rpalli** [comment]
I am having this same issue. Please fix @Zhiqiang-PANG. This is due to a warning which the causes the catch to try to execute a print() which then causes an error. The warning is in readRDS which gives the following warning "In readRDS("compound_db.rds") :
  strings not representable in native encoding will be translated to UTF-8". 

I was able to identify where the error originated because I see the following output from metaboAnalyst: 
[1] "Reading data unsuccessful, attempting to re-download file..."
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  557k  100  557k    0     0   557k      0  0:00:01 --:--:--  0:00:01  871k
[1] "Loading files from server unsuccessful. Ensure curl is downloaded on your computer."

This indicates that the file was initially found, then reading the file triggered the error function which then also could not execute.
