### ISSUE TITLE
Error in qs::qread("prenorm.qs")

### ISSUE THREAD

**Issue by TanyaV9** [xia-lab/MetaboAnalystR#179]
Greetings MetaboAnalystR users,

I am new to MetaboAnalyst and was trying to run a basic example, in order to learn its usage.

I was following the given example
library(MetaboAnalystR)
mSet<-InitDataObjects("conc", "stat", FALSE)
mSet<-Read.TextData(mSet, "http://www.metaboanalyst.ca/MetaboAnalyst/resources/data/human_cachexia.csv", "rowu", "disc");
mSet<-SanityCheckData(mSet);
mSet<-ReplaceMin(mSet);
mSet<-Normalization(mSet, "NULL", "LogNorm", "MeanCenter", "S10T0", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "norm_0_", format ="png", dpi=72, width=NA)
mSet<-PlotSampleNormSummary(mSet, "snorm_0_", format = "png", dpi=72, width=NA)

However, came forth with an error msg:
> mSet<-Normalization(mSet, "NULL", "LogNorm", "MeanCenter", "S10T0", ratio=FALSE, ratioNum=20)
Error in qs::qread("prenorm.qs") : 
  Failed to open prenorm.qs. Check file path.

Can anyone please guide me through, it will be of big help.

Eagerly looking forward for a response, 
Thanking you for your support,

**Comment by qqwxp** [comment]
I encountered the similar problem. Did you find a solution ?

**Comment by possumhound** [comment]
I had this issue too, this is my understanding: The MetaboAnalyst R code only works in conjunction with the data generated by the MetaboAnalyst platform. It is not stand alone code. So you need to do your analysis online using the MetaboAnalyst platform, then you need to download the zip file, and in that zip file you will find .RData file, your qs files and the Rhistory file. You need to load the .RData file into R in order to get the code from your Rhistory working. 

Also, I had to use setwd() before using the MetaboAnalyst code and then only put the file name in this section mSet<-Read.TextData(mSet, "file.csv", "colu", "disc") as I was getting an error when using the entire filepath in the MetaboAnalyst code (Error: $ operator is invalid for atomic vectors).

(The error you are getting is telling you that R cannot find the qs files. These qs files are in the Metaboanalyst download zip file. Maybe there's a way to create them using the source code found here: https://rdrr.io/github/xia-lab/MetaboAnalystR/src/R/general_norm_utils.R , but this is beyond my expertise)

**Comment by xia-lab** [comment]
See below, the "prenorm.qs" is generated in the step 5 based on the command history in MetaboAnalyst web, as well as in [our R tutorial](https://www.metaboanalyst.ca/docs/RTutorial.xhtml)): 

=====
1. | mSet<-InitDataObjects("conc", "stat", FALSE)
2. | mSet<-Read.TextData(mSet, "Replacing_with_your_file_path", "rowu", "disc");
3. | mSet<-SanityCheckData(mSet)
4. | mSet<-ReplaceMin(mSet);
5. | **mSet<-PreparePrenormData(mSet)**
6. | mSet<-Normalization(mSet, "NULL", "LogNorm", "NULL", ratio=FALSE, ratioNum=20)

**Comment by LFJM-dev** [comment]
Pertaining to xia-lab: Run line 4 on missing data, even if you do not have any missing data. That worked for me

**Comment by CM-07** [comment]
Hello,

mSet<-InitDataObjects("pktable", "stat", FALSE)
Starting Rserve:
 /Library/Frameworks/R.framework/Resources/bin/R CMD /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/Rserve/libs//Rserve --no-save 


R version 4.3.0 (2023-04-21) -- "Already Tomorrow"
Copyright (C) 2023 The R Foundation for Statistical Computing
Platform: aarch64-apple-darwin20 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[Previously saved workspace restored]

##> SOCK_ERROR: bind error #48(address already in use)
[1] "MetaboAnalyst R objects initialized ..."
> mSet<-Read.TextData(mSet, "metaboanalyst_input.csv", "rowu", "disc")
> mSet <- SanityCheckData(mSet)
[1] "A total of 7156 groups found with 7156 samples."
[1] "<font color='red'>At least <b>two</b> groups and <b>three replicates</b> per group are required for analysis</font>!"
[1] "You can click the <b>Edit Groups</b> button below to see the group labels for each sample and make corrections."
> print(mSet)
[1] -1
> mSet<-FilterVariable(mSetObj = mSet, "iqr", "F", 25)
Error in `*tmp*`$dataSet : $ operator is invalid for atomic vectors

I am concerned about the last error "Error in `*tmp*`$dataSet : $ operator is invalid for atomic vectors".

I couldn't find a way to deal with it. 

Any help is highly appreciated.

Thank you!
