### ISSUE TITLE
Error in tolower(cmpd.db$name) : invalid multibyte string 8534

### ISSUE THREAD

**Issue by wydty** [xia-lab/MetaboAnalystR#19]
Hi!

I was learning how to use this package and encountered an error while running the example(`vignettes/Pathway_Analysis.Rmd`).

```
library(MetaboAnalystR)
tmp.vec <- c("Acetoacetic acid", "Beta-Alanine", "Creatine", "Dimethylglycine", "Fumaric acid", "Glycine", "Homocysteine", "L-Cysteine", "L-Isolucine", "L-Phenylalanine", "L-Serine", "L-Threonine", "L-Tyrosine", "L-Valine", "Phenylpyruvic acid", "Propionic acid", "Pyruvic acid", "Sarcosine")

mSet<-InitDataObjects("conc", "pathora", FALSE)

mSet<-Setup.MapData(mSet, tmp.vec);

mSet<-CrossReferencing(mSet, "name");
#  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
#                                Dload  Upload   Total   Spent    Left  Speed
#100  282k  100  282k    0     0   124k      0  0:00:02  0:00:02 --:--:--  124k
#Error in tolower(cmpd.db$name) : invalid multibyte string 8534
```
thank you!

**Comment by jsychong** [comment]
Hi, 

Sorry for the delayed response I didn't get a message letting me know an issue had been opened. First, was the compound_db.rds file successfully downloaded and can it be found in your working directory? Second, are you using a Windows computer?

**Comment by YinCY123** [comment]
hi, It seems that all compounds IDs were stored in compound_db.rds file, so  i want to know where can i get the <compound_db.rds> file.

**Comment by jsychong** [comment]
The "compound_db.rds" file is the masterfile containing the mappings of all the metabolites to the PubChem IDs, HMDB IDs, etc. It should be downloaded to your current working directory when using the CrossReferencing function.

**Comment by bowenli37** [comment]
I encountered the same error:
 Error in tolower(cmpd.db$kegg_id[i]) : invalid multibyte string 1
The items that cause the error look like: 鈬?C04741

I found a solution at https://stackoverflow.com/questions/22876746/how-to-read-data-in-utf-8-format-in-r
Change your locale from "chinese" to "English_United States.1252"
 Sys.setlocale(category="LC_ALL", locale = "English_United States.1252")

**Comment by wenjiexiaomeng** [comment]
library(MetaboAnalystR)
mSet<-InitDataObjects("conc", "msetora", FALSE)
cmpd.vec<-c("Acetoacetic acid","Beta-Alanine","Creatine","Dimethylglycine","Fumaric acid","Glycine","Homocysteine","L-Cysteine","L-Isolucine","L-Phenylalanine","L-Serine","L-Threonine","L-Tyrosine","L-Valine","Phenylpyruvic acid","Propionic acid","Pyruvic acid","Sarcosine")
mSet<-Setup.MapData(mSet, cmpd.vec)
mSet<-CrossReferencing(mSet, "name")
##########################################
[1] "Loaded files from MetaboAnalyst web-server."
Error in tolower(cmpd.db$name) : invalid multibyte string 8534

The same error occurs again, could you give me a hand  about this ?

**Comment by Santos22903** [comment]
Hi,
I am not even sure this issue is still being supported, but it is not closed, so...
I was initially getting an error below with my compounds; to make sure it is not a problem with them, I repeated the steps from above:
library(MetaboAnalystR)
mSet<-InitDataObjects("conc", "msetora", FALSE)
cmpd.vec<-c("Acetoacetic acid","Beta-Alanine","Creatine","Dimethylglycine","Fumaric acid","Glycine","Homocysteine","L-Cysteine","L-Isolucine","L-Phenylalanine","L-Serine","L-Threonine","L-Tyrosine","L-Valine","Phenylpyruvic acid","Propionic acid","Pyruvic acid","Sarcosine")
mSet<-Setup.MapData(mSet, cmpd.vec)
mSet<-CrossReferencing(mSet, "name")

The message I got was:
 [1] "Loaded files from MetaboAnalyst web-server."
Error in tolower(cmpd.db$name) : invalid multibyte string 8533

I am using R version 4.0.3 on CentOS Linux 8
Thank you

**Comment by bowenli37** [comment]
The underlying reason is that the compound database (compound_db.qs) is encoded in UTF8, but on a Windows system, it reads qs file with native encoding that depends on your system locale. Although it is possible to set locale in R, but UTF8 locale is not supported in Windows. Then some Non-ASCII UTF8 codes will not be mapped to any valid character in the native encoding, which throws an error.

The solution is to convert the character to UTF8 after reading, or more precisely, explicitly tells R to mark the character encoding as UTF8.

cmpd.db$name <- iconv(cmpd.db$name, from = 'utf8', to = 'utf8')

It turns out that the character in the database is wrong. So another solution is to correct the character in R, and save it to qs file.

**Comment by kriswangchunyan** [comment]
yes, i add the code
Sys.setlocale(category="LC_ALL", locale = "English_United States.1252"),these is useful!!
